/*
 * application.c
 *
 *  Created on: Oct 20, 2020
 *      Author: max
 */

#include "main.h"
#include "cmsis_os2.h"
#include "stm32l4xx_hal_tim.h"
#include "stm32l4xx_hal_tim_ex.h"
#include "io.h"

// Declare external references to timer instances

extern TIM_HandleTypeDef htim1;

// Declaration of queues, defined in main.c

extern osMessageQueueId_t acquisitionQueueHandle;
extern osMessageQueueId_t displayQueueHandle;

// Event flag object, created in acquisition.c, used to start an ADC acquisition
extern osEventFlagsId_t acqEventFlagsHandle;

#define ACQ_FLAG_START (1U << 0)	// same flag used by the acquisition task

// Heater control objects, created at runtime by StartDefaultTask (see below).
// They are dynamically allocated because main.c (generated by CubeMX) cannot be edited.
osMessageQueueId_t heaterQueueHandle;	// carries the temperature to the heater task
osThreadId_t heaterTaskHandle;			// the heater control task

// Target temperature, in tenths of Kelvin (no float): 50 C = 323.1 K -> 3231.
// To turn this single-threshold control into a hysteretic one, replace the single
// comparison in StartHeaterTask with two thresholds (e.g. 3221 = 49 C / 3241 = 51 C).
#define HEATER_TARGET_KELVIN_X10 3231

// Sentinel pushed to the heater queue to force the heater OFF (a temperature well
// above the target), e.g. when monitoring is stopped.
#define HEATER_FORCE_OFF 0xFFFFU

// Forward declaration: the heater task is defined at the bottom of this file
void StartHeaterTask( void *argument );

// Callback used by the TIM1 on period interrupt
// Registered before starting timer1

void tim1Callback( TIM_HandleTypeDef *htim ) {
	(void)htim;	// unused, silence compiler warning
	// Scope marker pulse on IO10 (rising then falling edge)
	HAL_GPIO_WritePin( IO10_GPIO_GPIO_Port, IO10_GPIO_Pin, GPIO_PIN_SET );
	HAL_GPIO_WritePin( IO10_GPIO_GPIO_Port, IO10_GPIO_Pin, GPIO_PIN_RESET );
	// Wake up the acquisition task so it starts a new ADC conversion.
	// osEventFlagsSet is ISR-safe here (configUSE_OS2_EVENTFLAGS_FROM_ISR=1).
	// Guard against a NULL handle in case the timer fires before acquisition.c
	// has created the event flag object.
	if( acqEventFlagsHandle != NULL ) {
		osEventFlagsSet( acqEventFlagsHandle, ACQ_FLAG_START );
	}
}

void StartDefaultTask( void *argument ) {
	(void)argument;	// unused, silence compiler warning
	HAL_TIM_RegisterCallback(&htim1, HAL_TIM_PWM_PULSE_FINISHED_CB_ID, tim1Callback);

	// Create the heater queue and the heater control task at runtime.
	// Dynamic allocation is used because the static objects live in main.c, which
	// is generated by CubeMX and must not be edited. If creation fails the task is
	// simply not started: the default task keeps working as in Lab 3 (no crash).
	heaterQueueHandle = osMessageQueueNew( 1, sizeof( uint16_t ), NULL );
	const osThreadAttr_t heaterTask_attributes = {
		.name = "heaterTask",
		.stack_size = 256 * 4,	// 1024 bytes from the FreeRTOS heap (3000 bytes total)
		.priority = (osPriority_t) osPriorityNormal,
	};
	if( heaterQueueHandle != NULL ) {
		heaterTaskHandle = osThreadNew( StartHeaterTask, NULL, &heaterTask_attributes );
	}

	while( 1 ) {
		if( getSwitch0() ) { // Blink LEDs
			while( getSwitch0() ) {
				led0( OFF );
				led1( ON );
				led2( OFF );
				led3( ON );
				osDelay( 500 );
				led0( ON );
				led1( OFF );
				led2( ON );
				led3( OFF );
				osDelay( 500 );
			}
		} else if( getSwitch1() ) { // This must be filled by students, to perform requested functions
			HAL_TIM_PWM_Start_IT(&htim1, TIM_CHANNEL_1);
			//starts the timer in PWM mode on channel 1
			while( getSwitch1() ){
					uint16_t temperature;
					osStatus_t status = osMessageQueueGet(acquisitionQueueHandle, &temperature, NULL, osWaitForever);
					if(status == osOK){
						osMessageQueuePut(displayQueueHandle, &temperature, 0U, 0U);
						// Forward the same sample to the heater task as well.
						// Non-blocking put (timeout 0): never blocks, never crashes.
						if( heaterQueueHandle != NULL ){
							osMessageQueuePut(heaterQueueHandle, &temperature, 0U, 0U);
						}
					}
				}
				HAL_TIM_PWM_Stop_IT(&htim1, TIM_CHANNEL_1);

				// Safety: monitoring stopped, force the heater OFF so it is not
				// left on indefinitely with no temperature updates. A finite timeout
				// (100 ms, tick = 1 ms) makes the put reliable even if a stale sample
				// still occupies the depth-1 queue, without ever blocking forever.
				if( heaterQueueHandle != NULL ){
					uint16_t forceOff = HEATER_FORCE_OFF;
					osMessageQueuePut(heaterQueueHandle, &forceOff, 0U, 100U);
				}

			}
		}
}

// Heater control task entry point.
//
// Drives the low-side switch (2N2222) that powers the heater resistor, through a
// GPIO (IO11 / PE11). Single-threshold on/off temperature control as required by
// Lab 4: turn the heater ON when the measured temperature is below the target
// (50 C), turn it OFF otherwise. All values are in tenths of Kelvin (no float).

void StartHeaterTask( void *argument ) {
	(void)argument;	// unused, silence compiler warning

	// IO11 (PE11) is left as a plain INPUT by CubeMX (it is part of the GPIOE input
	// batch in main.c). Reconfigure it here as a push-pull output so we can drive
	// the transistor base resistor.
	LL_GPIO_InitTypeDef gpio = {0};
	gpio.Pin        = IO11_Pin;
	gpio.Mode       = LL_GPIO_MODE_OUTPUT;
	gpio.Speed      = LL_GPIO_SPEED_FREQ_LOW;
	gpio.OutputType = LL_GPIO_OUTPUT_PUSHPULL;
	gpio.Pull       = LL_GPIO_PULL_NO;
	LL_GPIO_Init(IO11_GPIO_Port, &gpio);

	// Start with the heater OFF
	HAL_GPIO_WritePin(IO11_GPIO_Port, IO11_Pin, GPIO_PIN_RESET);
	led0( OFF );	// status LED off: heater idle (reuses io.c)

	/* Infinite loop */
	for( ; ; ){
		uint16_t t_kelvin_x10;	// temperature, tenths of Kelvin
		// Block until a new temperature is available on the heater queue
		osStatus_t status = osMessageQueueGet(heaterQueueHandle, &t_kelvin_x10, NULL, osWaitForever);
		if( status == osOK ){
			if( t_kelvin_x10 < HEATER_TARGET_KELVIN_X10 ){
				// Below the target temperature: heat up
				HAL_GPIO_WritePin(IO11_GPIO_Port, IO11_Pin, GPIO_PIN_SET);	// T < 50 C -> ON
				led0( ON );		// LED on: heating
			} else {
				// At or above the target temperature: stop heating
				HAL_GPIO_WritePin(IO11_GPIO_Port, IO11_Pin, GPIO_PIN_RESET);	// T >= 50 C -> OFF
				led0( OFF );	// LED off: target reached
			}
		}
	}
}

